### ISSUE TITLE
Does this module rely on d3-geo?

### ISSUE THREAD

**Issue by Booonfire** [stamen/geo-albers-usa-territories#5]
I do not see d3-geo in the dependencies but it seems to require d3-geo.
I found this issue when I use broswerify trying to create the map on the frontend.

This is the error message:

> Error: Can't walk dependency graph: Cannot find module 'd3-geo' from '/node_modules/geo-albers-usa-territories/dist/geo-albers-usa-territories.js'
>     required by /node_modules/geo-albers-usa-territories/dist/geo-albers-usa-territories.js

**Comment by curran** [comment]
Good catch! Indeed, it should be a dependency, or maybe a `peerDependency`.

**Comment by curran** [comment]
@Booonfire Published as v0.1.0. Please let us know if this helps with your Browserify setup. Thanks!

**Comment by Booonfire** [comment]
> @Booonfire Published as v0.1.0. Please let us know if this helps with your Browserify setup. Thanks!

Thanks for your help. I noticed that d3-geo was added both in `devDependencies` and `peerDependency`. When I install, npm warns that I need to install peer dependencies myself. So I guess npm will treat d3-geo as a peerDependency by default right?

**Comment by curran** [comment]
That's right. Your code needs to independently have `d3-geo` as a dependency. This is to avoid pulling in multiple different copies of D3-geo with different versions.

I _think_ this is the recommended approach for libraries set up like this. I know it's a common practice with React for example, to mark React as both a peer dependency and a dev dependency, for libraries that expose reusable components.

**Comment by curran** [comment]
Alternatively it could be added as a dependency. I'm not sure if that might be best ... Open to advice!

**Comment by Booonfire** [comment]
> Alternatively it could be added as a dependency. I'm not sure if that might be best ... Open to advice!

That's acceptable. I would recommend mentioning it on the README.md.

**Comment by curran** [comment]
Added the following to README:

>Note that this package marks `d3-geo` as a `peerDependency`, so you'll need to directly depend on `d3-geo` as well as this package. This is to avoid the possibility of bundling multiple copies of `d3-geo`.
